CREATE TABLE tb_room (
    id bigint GENERATED BY DEFAULT as identity,
    name varchar(255) not null,
    capacity bigint not null,

    primary key (id)
);

comment on table tb_room is 'Has all the school rooms';
comment on column tb_room.name is  'The name of the room';
comment on column tb_room.capacity is 'The total of students that can be assigned to this room';