spring:
  application:
    name: api-gateway-service
  profiles:
    active: dev
  config:
    import: configserver:http://localhost:8888/
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: room-service
          uri: lb://room-service
          predicates:
            - Path=/rooms/**
          filters:
            - RewritePath=/rooms/(?<segment>.*), /rooms/$\{segment}
server:
  port: 8765
